name: gem5 Performance Test

on:
  push:
    branches: [ xs-dev ]
  pull_request:
    branches: [ xs-dev ]

jobs:
  perf_test:
    uses: ./.github/workflows/gem5-perf-template.yml
    with:
      script_path: ../kmh_6wide.sh